title: John Woodman's Security Blog
description: "I'm a security enthusiast looking for new ways to break stuff and stay hidden
  while doing it. All content posted here is for educational and research
  purposes only. "
author:
  name: "John Woodman"
  email: "john.woodman11@gmail.com"
  url: "https://google.com/"

baseurl: /

source: .
destination: ./_site
permalink: /:categories/:title/
#paginate: 3
#paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-paginate-multiple

paginate_multiple:
  - paginate: 3
    paginate_path: '/page:num/'
    sub_dir: '/research'
  - paginate: 3
    paginate_path: '/hackthebox/page:num/'
    sub_dir: '/hackthebox'
  - paginate: 3
    paginate_path: '/ctf/page:num/'
    sub_dir: '/ctf'

# Custom variables
owner : "John Woodman"
year : "2019"
exclude: ["build_prod.sh"]
include: ['.htaccess']
google_analytics: "UA-154967710-1" 
